import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { bountiesRouter } from "./bounties";
import { researchRouter } from "./research";
import { productionRouter } from "./production";
import { submissionsRouter } from "./submissions";
import { earningsRouter } from "./earnings";
import { dashboardRouter } from "./dashboard";
import { settingsRouter } from "./settings";
import { discoverRouter } from "./discover";
import { adminRouter } from "./admin";
import { mcpRouter } from "./mcp";
import devpostRouter from "./devpost";
import dextopusRouter from "./dextopus";
import { referralsRouter } from "./referrals";
import { customBountiesRouter } from "./custom-bounties";
import { gamificationRouter } from "./gamification";
import { checkinRouter } from "./checkin";
import { notificationsRouter } from "./notifications";
import { agentRouter } from "./agent";
import { telegramRouter } from "./telegram";
import { bountyEntriesRouter } from "./bounty-entries.js";
import ramphubRouter from "./ramphub.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/bounties", bountiesRouter);
router.use("/research-briefs", researchRouter);
router.use("/production-plans", productionRouter);
router.use("/submissions", submissionsRouter);
router.use("/earnings", earningsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/settings", settingsRouter);
router.use("/discover", discoverRouter);
router.use("/admin", adminRouter);
router.use("/mcp", mcpRouter);
router.use("/devpost", devpostRouter);
router.use("/dextopus", dextopusRouter);
router.use("/referrals", referralsRouter);
router.use("/custom-bounties", customBountiesRouter);
router.use("/gamification", gamificationRouter);
router.use("/checkin", checkinRouter);
router.use("/notifications", notificationsRouter);
router.use("/agent", agentRouter);
router.use("/telegram", telegramRouter);
router.use("/bounty-entries", bountyEntriesRouter);
router.use("/ramphub", ramphubRouter);

export default router;
