#!/usr/bin/env bash
# Complete migration script: Replit -> Supabase + Render + Vercel
# Run each step individually after setting up the new services

set -e

echo "=========================================="
echo "BountyPilot Migration Guide"
echo "=========================================="
echo ""
echo "STEP 1: Export your Replit database"
echo "------------------------------------"
echo "Run this in your Replit shell:"
echo "  bash scripts/export-db.sh > db-export-full.sql"
echo ""
echo "STEP 2: Set up Supabase"
echo "-----------------------"
echo "1. Go to https://supabase.com and create a free project"
echo "2. Open the SQL Editor in your Supabase project"
echo "3. Run the contents of scripts/supabase-schema.sql"
echo "4. Then run the contents of db-export-full.sql"
echo ""
echo "STEP 3: Get your Supabase connection string"
echo "-------------------------------------------"
echo "In Supabase Dashboard -> Settings -> Database:"
echo "Copy the connection string (use the 'pooler' connection for serverless)"
echo "It looks like: postgresql://postgres.[project]:[password]@aws-0-[region].pooler.supabase.com:5432/postgres"
echo ""
echo "STEP 4: Deploy API Server to Render"
echo "------------------------------------"
echo "1. Go to https://render.com and create a Blueprint"
echo "2. Connect your GitHub repo"
echo "3. Set the following environment variables in Render Dashboard:"
echo "   - DATABASE_URL: (your Supabase connection string)"
echo "   - JWT_SECRET: (generate with: openssl rand -base64 32)"
echo "   - QWEN_API_KEY: (your Qwen API key)"
echo ""
echo "STEP 5: Update Vercel frontend"
echo "------------------------------"
echo "1. In Vercel project settings, add environment variable:"
echo "   - VITE_API_BASE_URL: https://bountypilot-api.onrender.com/api"
echo "2. Or update the API_BASE in auth.tsx to use the Render API URL"
echo ""
echo "STEP 6: Test"
echo "------------"
echo "1. Sign up on your Vercel app"
echo "2. Check the data appears in Supabase SQL Editor"
echo "3. Verify all 70 users are migrated correctly"
echo ""
echo "For help: Run each step above and verify the connection"
echo "=========================================="
